### ISSUE TITLE
failing (exits with 1) to fetch references for the client job

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#154]
```
yhalchen@openmind7:~
$> cd ~/git-annex-ci/git-annex/clients && flock -n -E 0 .lock venv/bin/python testannex.py `hostname` ~/git-annex-ci/jobs
total 44
 4 clients.yaml      4 mktable.py   4 requirements.txt   4 testannex.sh*   0 venv/
 4 environment.yml   8 README.md   12 testannex.py       4 testlib.sh
2023-02-10 16:16:51 [INFO    ] testannex: Updating client config repo ...
From http://github.com/datalad/git-annex
 * branch            master     -> FETCH_HEAD
Already up-to-date.
2023-02-10 16:16:52 [INFO    ] testannex: Updating master branch of job repo
Already on 'master'
From github.com:datalad/git-annex-ci-client-jobs
 * branch            master     -> FETCH_HEAD
Already up-to-date.
2023-02-10 16:16:53 [INFO    ] testannex: Fetching jobs ...
fatal: Invalid refspec '+refs/heads/build-openmind7-*:refs/remotes/origin/build-openmind7-*'
Traceback (most recent call last):
  File "testannex.py", line 284, in <module>
    main()
  File "/home/yhalchen/git-annex-ci/git-annex/clients/venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/yhalchen/git-annex-ci/git-annex/clients/venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/yhalchen/git-annex-ci/git-annex/clients/venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yhalchen/git-annex-ci/git-annex/clients/venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "testannex.py", line 157, in main
    f"+refs/heads/build-{clientid}-*:refs/remotes/origin/build-{clientid}-*",
  File "testannex.py", line 77, in run
    return runcmd("git", *args, **kwargs)
  File "testannex.py", line 272, in runcmd
    return subprocess.run(argstrs, **kwargs)
  File "/home/yhalchen/.conda/envs/datalad/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'fetch', '--prune', 'origin', '+refs/heads/build-openmind7-*:refs/remotes/origin/build-openmind7-*']' returned non-zero exit status 128.

$> echo $?
1
```

I think it was a first ever cron job ran on that client.  But before that I ran it and I think it quietly said just that there is nothing to do for that client . @jwodder -- what do you think is going on?

**Comment by yarikoptic** [comment]
I believe so , indeed way too old
```
$> git --version
git version 1.8.3.1
```
I will need to make it use newer one from conda env I guess.

**Comment by yarikoptic** [comment]
Thank you @jwodder ! I've sent it as a PR

**Comment by yarikoptic** [comment]
as of https://github.com/datalad/git-annex/issues/155 where I do see the builds, I think we are good now (I used conda env on openmind)

**Comment by jwodder** [comment]
@yarikoptic Is this still a problem?

**Comment by yarikoptic** [comment]
No, iirc I overcome with using conda env with more up to date git.
Thanks for the buzz!
